# Generated by Django 5.2.17 on 2026-08-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje', models.CharField(default='Eje A - Gobernanza', max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(choices=[('Directa', 'Directa'), ('Compartida', 'Compartida'), ('Delegada/Concesionada', 'Delegada/Concesionada'), ('Indirecta', 'Indirecta'), ('No aplica', 'No aplica')], max_length=30, verbose_name='Tipo de competencia municipal')),
                ('madurez', models.CharField(choices=[('0', '0 - No existe'), ('1', '1 - En planificación'), ('2', '2 - Implementación parcial'), ('3', '3 - Implementación consolidada'), ('4', '4 - Referente o mejora continua')], max_length=2, verbose_name='Nivel de madurez (0-4)')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Formulario.diagnostico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.pregunta')),
            ],
        ),
    ]
